# Generated by Django 5.2.4 on 2025-07-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='consolas/'),
        ),
    ]
