# Generated by Django 5.2.4 on 2025-07-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_consolas_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='consolas_img/'),
        ),
    ]
